language: csharp
sudo: required
mono: none
dotnet: 2.0.0
script:
- dotnet --version
- dotnet restore
- dotnet build
- dotnet test tests/Qberry.Open.Protocol.Parsing.UnitTest/Qberry.Open.Protocol.Parsing.UnitTest.csproj